name: Integration Test

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        # Put your action repo here
        - uses: stephend017/ghapd@main
          with:
            owner_name: 'stephend017'
            repository_name: 'repository_name'
            personal_access_token: ${{ secrets.GH_PAT }}
